In [1]:
documents = [
  "Quantum mechanics describes the behavior of very small particles.",
  "Photosynthesis is the process by which green plants make food using sunlight.",
  "Shakespeare's plays are a testament to English literature.",
  "Artificial Intelligence aims to create machines that can think and learn.",
  "The pyramids of Egypt are historical monuments that have stood for thousands of years.",
  "Biology is the study of living organisms and their interactions with the environment.",
  "Music therapy can aid in the mental well-being of individuals.",
  "The Milky Way is just one of billions of galaxies in the universe.",
  "Economic theories help understand the distribution of resources in society.",
  "Yoga is an ancient practice that involves physical postures and meditation."
]


In [2]:
documents

['Quantum mechanics describes the behavior of very small particles.',
 'Photosynthesis is the process by which green plants make food using sunlight.',
 "Shakespeare's plays are a testament to English literature.",
 'Artificial Intelligence aims to create machines that can think and learn.',
 'The pyramids of Egypt are historical monuments that have stood for thousands of years.',
 'Biology is the study of living organisms and their interactions with the environment.',
 'Music therapy can aid in the mental well-being of individuals.',
 'The Milky Way is just one of billions of galaxies in the universe.',
 'Economic theories help understand the distribution of resources in society.',
 'Yoga is an ancient practice that involves physical postures and meditation.']

# Building Robust Semantic Search Engines with Transformers model

In [3]:
!pip install -U sentence-transformers

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 249.1/249.1 kB 9.3 MB/s eta 0:00:00


In [4]:
!nvidia-smi

Sat Sep 14 07:14:49 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [5]:
from sentence_transformers import SentenceTransformer, util
import torch

/usr/local/lib/python3.10/dist-packages/sentence_transformers/cross_encoder/CrossEncoder.py:13: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange


In [6]:
# Load pre-trained transformers model

model = SentenceTransformer('all-MiniLM-L6-v2')

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.7k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [7]:
model

SentenceTransformer(
  (0): Transformer({'max_seq_length': 256, 'do_lower_case': False}) with Transformer model: BertModel 
  (1): Pooling({'word_embedding_dimension': 384, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
  (2): Normalize()
)

In [8]:
len(documents)

10

In [9]:
document_embedding = model.encode(documents)

In [10]:
document_embedding.shape

(10, 384)

In [11]:
document_embedding[1]

array([-5.48190512e-02,  6.03153408e-02, -6.25312477e-02,  3.30856219e-02,
        3.27017419e-02, -1.57242059e-03,  1.79645345e-02, -4.08752970e-02,
        5.32725081e-02,  5.96406944e-02,  7.29455128e-02, -2.25856509e-02,
       -1.52777964e-02, -7.15794414e-02,  6.52469024e-02,  3.46195363e-02,
       -3.13290507e-02,  3.49413678e-02, -5.50261177e-02, -7.35656843e-02,
        2.50069518e-02, -1.73191796e-03, -4.25948873e-02, -4.92940843e-02,
        1.17692724e-02, -6.46106433e-03, -7.40840882e-02, -4.41866256e-02,
        5.15968353e-03, -4.80130780e-04,  2.52962522e-02,  1.83929838e-02,
        1.63323302e-02,  3.59010696e-02, -5.12360409e-03,  8.94818604e-02,
        6.01719320e-02, -1.74312919e-01, -4.73888852e-02,  2.37061959e-02,
       -4.15138043e-02, -6.67382553e-02, -4.59151417e-02,  3.66581902e-02,
       -2.98727769e-02, -1.75096299e-02, -3.25327478e-02,  2.43602730e-02,
       -6.44422397e-02, -1.35005176e-01, -4.20406051e-02, -1.23574547e-02,
       -8.54972973e-02, -

In [12]:
documents[1]

'Photosynthesis is the process by which green plants make food using sunlight.'

In [13]:
# Let's try to find the most similar document for one query
new_query = "what is AI?"
new_query

'what is AI?'

In [14]:
# Get embedding for new query
next_text_embedding = model.encode(new_query)
next_text_embedding

array([-2.49644294e-02, -9.13366675e-03, -7.46155018e-03,  1.50090652e-02,
        1.33104008e-02, -1.00360438e-02,  7.45601356e-02,  4.26714569e-02,
        1.69885065e-02,  5.59509546e-02, -2.96819080e-02, -4.35607787e-03,
        2.05323361e-02, -4.82827090e-02, -5.86694703e-02,  4.23620231e-02,
       -1.89194735e-02, -5.29925190e-02, -8.71717334e-02, -6.99818581e-02,
       -8.72021820e-03,  1.96782555e-02, -4.86003831e-02, -4.87065464e-02,
       -3.24669331e-02,  9.29557160e-02,  4.01412556e-03, -6.72163144e-02,
       -2.18765275e-03, -1.11629646e-02,  1.21077262e-02, -2.36866456e-02,
        1.02300443e-01,  1.91985052e-02, -6.65093437e-02,  4.12883870e-02,
       -4.09804024e-02, -2.75316685e-02,  6.85106069e-02, -2.96445526e-02,
       -1.92079283e-02, -5.42026609e-02,  1.68526936e-02, -7.19662681e-02,
        1.08496055e-01,  1.24557033e-01, -7.32609704e-02, -1.34330308e-02,
        3.10076419e-02,  5.09724393e-02, -1.31916091e-01, -1.21613510e-03,
       -5.76595543e-03,  

In [15]:
documents

['Quantum mechanics describes the behavior of very small particles.',
 'Photosynthesis is the process by which green plants make food using sunlight.',
 "Shakespeare's plays are a testament to English literature.",
 'Artificial Intelligence aims to create machines that can think and learn.',
 'The pyramids of Egypt are historical monuments that have stood for thousands of years.',
 'Biology is the study of living organisms and their interactions with the environment.',
 'Music therapy can aid in the mental well-being of individuals.',
 'The Milky Way is just one of billions of galaxies in the universe.',
 'Economic theories help understand the distribution of resources in society.',
 'Yoga is an ancient practice that involves physical postures and meditation.']

In [16]:
# Get Cosine Similarity Score of Document Embedding compared to New Query Embedding
cos_score = util.pytorch_cos_sim(next_text_embedding, document_embedding)[0]
cos_score

tensor([0.0899, 0.0313, 0.0684, 0.6847, 0.0199, 0.1553, 0.0797, 0.0424, 0.1250,
        0.1547])

In [17]:
top_result = torch.topk(cos_score, k=1)
top_result

torch.return_types.topk(
values=tensor([0.6847]),
indices=tensor([3]))

In [18]:
idx = top_result.indices[0]
idx

tensor(3)

In [19]:
# Get most similar document
documents[idx]

'Artificial Intelligence aims to create machines that can think and learn.'

# Create a function to return the top similar document based on any query

In [21]:
def semantic_search_engine(query, embedder_model):
  query_embedding = embedder_model.encode(query)
  cos_score = util.pytorch_cos_sim(query_embedding, document_embedding)[0]
  top_result = torch.topk(cos_score, k=1)
  idx = top_result.indices[0]
  return documents[idx]


In [28]:
# Try out the function
new_sentence = "Tell me about AI"
sentence2 = "Do you know about the Pyramids"
sentence3 = "How do plants survive?"
sentence4="what about english litrature?"
sent4 ="what about Rahul Gandhi?"

In [24]:
semantic_search_engine(new_sentence, model)

'Artificial Intelligence aims to create machines that can think and learn.'

In [25]:
semantic_search_engine(sentence2, model)

'The pyramids of Egypt are historical monuments that have stood for thousands of years.'

In [26]:
semantic_search_engine(sentence3, model)

'Photosynthesis is the process by which green plants make food using sunlight.'

In [27]:
semantic_search_engine(sentence4, model)

"Shakespeare's plays are a testament to English literature."

In [29]:
semantic_search_engine(sent4, model)

'Quantum mechanics describes the behavior of very small particles.'